# Generated by Django 5.2.16 on 2026-08-09 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_user_fk_cascade_to_set_null_protect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["user"], name="att_rec_user_idx"),
        ),
    ]
