# Generated by Django 5.2.16 on 2026-08-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_add_attendance_record_user_index"),
        ("scheduling", "0004_class_sub_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="class_obj",
            field=models.ForeignKey(
                db_column="class_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_sessions",
                to="scheduling.class",
            ),
        ),
    ]
