# Generated by Django 5.0.9 on 2026-05-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Training Management System', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('brand_color', models.CharField(default='#4F46E5', max_length=7)),
                ('doc_max_mb', models.PositiveIntegerField(default=25)),
                ('image_max_mb', models.PositiveIntegerField(default=10)),
                ('video_max_mb', models.PositiveIntegerField(default=500)),
                ('reminder_offsets', models.JSONField(default=list)),
                ('session_lifetime_hours', models.PositiveIntegerField(default=24)),
            ],
            options={
                'verbose_name': 'System Settings',
                'db_table': 'common_system_settings',
            },
        ),
    ]
