# Generated by Django 5.2.16 on 2026-08-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_rename_sub_mentor_visibility_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="brand_color",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="product_name",
        ),
    ]
