# Generated by Django 5.2.16 on 2026-08-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_remove_product_name_brand_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="doc_max_mb",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="image_max_mb",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="video_max_mb",
        ),
    ]
