# Generated by Django 5.0.9 on 2026-05-18 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline Reminder'), ('TASK_OPENED', 'Task Opened'), ('SHARED_DOC_RESULT', 'Shared Doc Result'), ('ATTENDANCE_SESSION_STARTED', 'Attendance Session Started'), ('ATTENDANCE_SESSION_ENDED', 'Attendance Session Ended')], max_length=40)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App')], default='IN_APP', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent')], default='SENT', max_length=10)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notif_user_read_idx'), models.Index(fields=['user', 'created_at'], name='notif_user_created_idx'), models.Index(fields=['dedupe_key'], name='notif_dedupe_idx')],
            },
        ),
    ]
