# Generated by Django 5.0.9 on 2026-05-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline Reminder'), ('TASK_OPENED', 'Task Opened'), ('SHARED_DOC_RESULT', 'Shared Doc Result'), ('ATTENDANCE_SESSION_STARTED', 'Attendance Session Started'), ('ATTENDANCE_SESSION_ENDED', 'Attendance Session Ended'), ('GROUP_ADDED', 'Added to Group')], max_length=40),
        ),
    ]
