# Generated by Django 5.0.9 on 2026-05-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_group_added_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline Reminder'), ('TASK_OPENED', 'Task Opened'), ('SHARED_DOC_RESULT', 'Shared Doc Result'), ('CLASS_SCHEDULED', 'Class Scheduled'), ('CLASS_STARTING_SOON', 'Class Starting Soon'), ('ATTENDANCE_SESSION_STARTED', 'Attendance Session Started'), ('ATTENDANCE_SESSION_ENDED', 'Attendance Session Ended'), ('GROUP_ADDED', 'Added to Group')], max_length=40),
        ),
    ]
