# Generated by Django 5.0.9 on 2026-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_class_action_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline Reminder'), ('TASK_OPENED', 'Task Opened'), ('SHARED_DOC_RESULT', 'Shared Doc Result'), ('CLASS_SCHEDULED', 'Class Scheduled'), ('CLASS_STARTING_SOON', 'Class Starting Soon'), ('CLASS_RESCHEDULED', 'Class Rescheduled'), ('CLASS_DOCUMENT_ADDED', 'Class Document Added'), ('CLASS_TASK_ASSIGNED', 'Task Assigned to Class'), ('ATTENDANCE_SESSION_STARTED', 'Attendance Session Started'), ('ATTENDANCE_SESSION_ENDED', 'Attendance Session Ended'), ('ATTENDANCE_CLOSING_SOON', 'Attendance Closing Soon'), ('ATTENDANCE_OVERRIDE', 'Attendance Override'), ('GROUP_ADDED', 'Added to Group'), ('INVITE_RESENT', 'Invite Resent')], max_length=40),
        ),
    ]
