# Generated by Django 5.2.16 on 2026-08-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_user_fk_cascade_to_set_null_protect"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_dedupe_idx",
        ),
    ]
