# Generated by Django 5.2.16 on 2026-07-30 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduling", "0004_class_sub_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("comment", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="scheduling.class",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["class_session", "submitted_at"],
                        name="fb_session_submitted_idx",
                    ),
                    models.Index(
                        fields=["participant", "submitted_at"],
                        name="fb_participant_submitted_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("class_session", "participant"),
                        name="uniq_feedback_session_participant",
                    )
                ],
            },
        ),
    ]
