# Generated by Django 5.2.16 on 2026-08-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_user_fk_cascade_to_set_null_protect"),
        ("scheduling", "0004_class_sub_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classfeedback",
            name="class_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedbacks",
                to="scheduling.class",
            ),
        ),
    ]
