# Generated by Django 5.0.9 on 2026-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_unit",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="grade_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
