# Generated by Django 5.0.9 on 2026-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_business_unit_user_department_user_grade_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employee_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
