# Generated by Django 5.0.9 on 2026-06-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_group_admin_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordsetuptoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="passwordsetuptoken",
            index=models.Index(fields=["expires_at"], name="pst_expires_idx"),
        ),
    ]
