# Generated by Django 5.0.9 on 2026-06-15 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_groupadmin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subgroupmembership",
            index=models.Index(fields=["user"], name="sgm_user_idx"),
        ),
    ]
