# Generated by Django 5.2.16 on 2026-07-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0007_rename_mentor_content_types_and_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
