# Generated by Django 5.2.16 on 2026-08-08 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0008_add_location_to_classgroup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupleadmentor",
            name="lead_mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead_mentor_of_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupsubmentor",
            name="sub_mentor",
            field=models.ForeignKey(
                limit_choices_to={"role": "SUB_MENTOR"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_mentored_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subgroupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_group_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
