# Generated by Django 5.2.16 on 2026-08-09 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def convert_groupsubmentor_pk_to_uuid(apps, schema_editor):
    """
    Convert GroupSubMentor.id from BigAutoField to UUIDField.
    PostgreSQL IDENTITY columns cannot be directly cast to uuid; must drop the
    identity and then alter the column type with a gen_random_uuid() USING clause.
    SQLite (used in tests) handles this via Django's schema editor alter_field.
    """
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE "groups_groupsubmentor" '
            'ALTER COLUMN "id" DROP IDENTITY IF EXISTS, '
            'ALTER COLUMN "id" DROP DEFAULT'
        )
        schema_editor.execute(
            'ALTER TABLE "groups_groupsubmentor" '
            'ALTER COLUMN "id" TYPE uuid USING gen_random_uuid()'
        )
    else:
        GroupSubMentor = apps.get_model('groups', 'GroupSubMentor')
        old_field = GroupSubMentor._meta.pk
        new_field = models.UUIDField(
            primary_key=True, default=uuid.uuid4, editable=False
        )
        new_field.set_attributes_from_name('id')
        new_field.model = GroupSubMentor
        schema_editor.alter_field(GroupSubMentor, old_field, new_field)


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0009_user_fk_cascade_to_set_null_protect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupsubmentor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subgroup",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="subgroupmembership",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="groupleadmentor",
            name="lead_mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_mentor_of_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # T03-026: bigint→uuid PK — uses SeparateDatabaseAndState so the ORM
        # state is updated via AlterField while the DB change is handled
        # per-backend in the RunPython.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="groupsubmentor",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    convert_groupsubmentor_pk_to_uuid,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="groupsubmentor",
            constraint=models.UniqueConstraint(
                fields=("group", "sub_mentor"), name="uniq_group_sub_mentor"
            ),
        ),
        migrations.AddConstraint(
            model_name="subgroup",
            constraint=models.UniqueConstraint(
                fields=("parent_group", "name"), name="uniq_subgroup_name_per_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="subgroupmembership",
            constraint=models.UniqueConstraint(
                fields=("sub_group", "user"), name="uniq_subgroup_membership"
            ),
        ),
    ]
