# Generated by Django 5.0.9 on 2026-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='allow_late_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='attendance_close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='attendance_open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
